### ISSUE TITLE
Last page error - Bad InfiniteScroll path option. Next link not found

### ISSUE THREAD

**Issue by einkoro** [metafizzy/infinite-scroll#691] opened 2017-07-17 00:44 UTC
If you load the last page of results directly where the `path` selector will no longer match any nodes it will throw the following error:

```
Bad InfiniteScroll path option. Next link not found: .page-numbers .next
Disabling InfiniteScroll
Uncaught TypeError: this.getPath is not a function
```

``` js
$( '.archive .products' ).infiniteScroll( {
    path: '.page-numbers .next',
    append: '.product',
    debug: true
} );
```

Test case: http://mmcurate.com/test/test-case-page-2.html

**Comment by desandro** [comment] 2017-07-19 13:24
Thanks for reporting this issue! I'll be adding a fix in the next release that will stop if `getPath` has not been set. Thanks so much for proving a test case 😄

**Comment by ogabrielsantos** [comment] 2017-07-30 23:33
When a new release is planned @desandro?

**Comment by desandro** [comment] 2017-08-04 13:49
[v3.0.1](https://github.com/metafizzy/infinite-scroll/releases/tag/v3.0.1) has been released with this fix added. Please update! Closing this issue has resolved 🌈🐻

**Comment by ogabrielsantos** [comment] 2017-09-15 21:09
Receiving same error when we have only one page.

**Comment by raihan004** [comment] 2017-10-16 06:20
this issue isn't fixed yet, or did miss something?
I'm using latest version.

**Comment by zuicis** [comment] 2017-10-24 10:38
Version: Infinite Scroll PACKAGED v3.0.2

Bad InfiniteScroll path option. Next link not found: .next a
Disabling InfiniteScroll

Issue on
a) on first page (if second not exist (small record count or user filtered content))
b) on last page (if you have multiple pages)

`'pluginOptions' => [
    'prefill' => true,
    'append' => '.items > li',
    'history' => true,
    'path' => '.next a',          
    'debug' => false,
    'status' => '.page-load-status',
    //'hideNav' => '.pagination',
],`

**Comment by zuicis** [comment] 2017-10-24 10:50
Version: Infinite Scroll PACKAGED v3.0.2

Bad InfiniteScroll path option. Next link not found: .next a
Disabling InfiniteScroll

Issue on
a) on first page (if second not exist (small record count or user filtered content))
b) on last page (if you have multiple pages)

'pluginOptions' => [
	'prefill' => true,
	'append' => '.items > li',
	'history' => true,
	'path' => '.next a',
	'debug' => false,
	'status' => '.page-load-status',
	//'hideNav' => '.pagination',
],

**Comment by vahidrk** [comment] 2017-11-02 16:46
Same issue here. Also in my case, pagination and loader both get visible.

**Comment by kavin-90** [comment] 2017-11-11 12:11
same issue here.

**Comment by desandro** [comment] 2018-01-12 18:10
To be clear, The `Uncaught TypeError: this.getPath is not a function` should be fixed as of v3.0.2. The other error messages still occur.

As of v3.0.2 the intended behavior is on last pages where Infinite Scroll is initialized and `path` is set to a selector string, and that selected element is not available; Infinite Scroll will log two error messages:

```
Bad InfiniteScroll path option. Next link not found: .pagination__next
Disabling InfiniteScroll
```

These are error messages and not thrown JS errors, so they will not disrupt JS. These messages are useful for users who have set `path` to the wrong element, or are trying to use Infinite Scroll on a page with out a next link in the HTML.

**Closed** 2020-12-06 01:18 UTC

**Comment by PetrDlouhy** [comment] 2022-03-30 13:52
I don't think, that this is fixed properly, not even in 4.0.1.

When the single page result is loaded, `infinite-scroll` doesn't modify the `page-load-status` and doesn't hide pagination.

**Comment by PetrDlouhy** [comment] 2022-03-30 14:40
I found out, that `infinite-scroll` probably expects those controls to be hidden on page load. This fixed the problem for me:
```javascript
   $('.pagination').hide();
   $('.page-load-status').hide();
```

**Comment by subfighter3** [comment] 2023-07-12 17:46
> ```js
> if ( document.querySelector('.pagination__next') ) {
>   var infScroll = new InfiniteScroll({
>     path: '.pagination__next',
>   });
> }
> ```

I tried to add this conditional but it broke the infinite scroll capability to load next pages in Safari only!

Here a screenshot of what happen with the conditional applied in Safari (left) and Firefox (right).
Looks like enclosing the `infScroll` variable in the conditional block prevent infinite scroll to load the following pages!

![Screenshot 2023-07-12 at 19 25 37](https://github.com/metafizzy/infinite-scroll/assets/17915306/69a5f1f4-d2f9-47cb-bbda-3e6b3ac09537)

That said, probably it's not a good practice to enclose the infinite scroll code in a conditional, and maybe the "red" errors might become "yellow" alerts instead?
