### ISSUE TITLE
Script strips out last 0 symbol from next url to load

### ISSUE THREAD

**Issue by Boxy5** [metafizzy/infinite-scroll#700] opened 2017-08-06 16:34 UTC
Tried to use this script v3.0.1, but encountered an error. If you have zero(s) (0) in next url to load, script strips out last zero symbol (0) from url and cannot load that page to append to container and logs error in console.
Example; url xxxx/xxxx02017 becomes xxxx/xxxx0217.
How to fix this? Urgent problem!

**Comment by Boxy5** [comment] 2017-08-07 14:01
Thanks for reply! I'm nit very good in programming. :(
Would you tell me how to get that done? I tried to set path in that way
path: '.pagination__next'
where href of element with class .pagination__next contains right url that we need to append to container without any parsing.
Big thanks in advance!

**Comment by desandro** [comment] 2017-08-08 18:43
You'll need a way to get the next page's URL for each page load. If you have a live URL I can better understand your problem.  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by matthewmcvickar** [comment] 2017-08-16 22:32
Yeah, this is a problem with the `path` option 'smart' parsing behavior, which has boggled the people in #688 and #693.

The [instructions for the `path` option](https://infinite-scroll.com/options.html#path) seem to indicate that the `path` option just grabs the URL in the container and uses that:

> Set to a selector string of a link to the next page to use its `href` value.
> ```
> path: '.pagination__next'
> // parse href of element
> // => /page/2, /page/3, page/4 ...
> ```

When in fact it does some auto-detection after grabbing that URL to see if that URL contains a number that should be automatically incremented after each load. The 'parse' in the `parse href of element` code comment is what tipped me off to this (in addition to the comments on #688 and #693).

## Examples

I have two examples, both of which I don't really know how to replicate in a CodePen because they rely on numbers in URLs specific to my case.

### on my local machine:

When I run Infinite Scroll with history enabled (the default) on my local machine at the URL `http://localhost:3000`, I get this JS error in the console. It seems to be chopping off the final two `0`s in the port number.

```
[InfiniteScroll] cannot set history with different origin: http://localhost:30 on http://localhost:3000 . History behavior disabled.
```

And when I trigger load on that page, it tries to fetch the URL `http://localhost:30/foo-bar-baz/` instead of `http://localhost:3000/foo-bar-baz/`, again truncating the URL.

### on staging:

Our site domain contains a number. Let's call it `1stexamplesite.com`. When I run Infinite Scroll on our staging  domain, which is `ww2.1stexamplesite.com`, I get this error:

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
ww2.2stexamplesite.com/foo-bar-baz/
```

In this case it has replaced the `1` in the domain name with a `2`.

## How to fix this

So if your URL has a number in it, it might get parsed wrong, and the safest way to just grab the URL is to use the function version of the `path` option.

I was able to get around my issues by creating a small function for `path` that essentially recreates its expected default behavior:

**Doesn't work** for URLs with numbers:
`path: '.pagination__next a'`

**DOES work** for URLs with numbers:
`path: function() { return $('.pagination__next a').attr('href'); }`

@Boxy5, this is probably what you need. (Keep in mind this is jQuery, so you'll need a different function for 'vanilla JS.')

After doing this, I discovered this is exactly how @desandro proposes to get around this in https://github.com/metafizzy/infinite-scroll/issues/688#issuecomment-316403688.

**Comment by desandro** [comment] 2017-08-18 19:17
@matthewmcvickar Thanks for providing more insight here. I've added a qualifier for using [`path` with an element selector](https://infinite-scroll.com/options.html#path)

> Set to a selector string of a link to the next page to use its href value **for incremental page numbers (2, 3, 4...).**

I may need to better point to the function setting.

**Comment by desandro** [comment] 2018-01-02 17:22
I'm closing this issue as a duplicate of #688. See discussion there.

**Closed by desandro** 2018-01-02 17:22 UTC
