### ISSUE TITLE
Uncaught TypeError: this.button.destory is not a function at n.e.destroy.button

### ISSUE THREAD

**Issue by Smashr** [metafizzy/infinite-scroll#697] opened 2017-07-30 10:48 UTC
Getting this error on destroy:

Uncaught TypeError: this.button.destory is not a function
    at n.e.destroy.button

I believe its a typo and would be fixed by changing "destory" to "destroy" in the code.

Thanks.

**Comment by Smashr** [comment] 2017-07-30 10:54
So I updated the code in my environment and changed "destory" to "destroy", but that just results in more errors.

Basically, when a button is specified, and infiniteScroll is destroyed, there are errors:

"Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present."

**Comment by desandro** [comment] 2017-08-04 13:36
Duplicate of #686

This is a bug that will be resolved in the next release

**Closed by desandro** 2017-08-04 13:36 UTC
