### ISSUE TITLE
Infinite Scroll + Isotope + Safari + imagesLoaded - reproducible with official demo code

### ISSUE THREAD

**Issue by jason-pomerleau** [metafizzy/infinite-scroll#699] opened 2017-08-03 18:54 UTC
**Official test case:** https://codepen.io/desandro/pen/eRRQVo
**My test case:** https://demo.dmopress.com/windsoreats/

I've been a bit stuck with a Safari-only issue (iOS and MacOS) using Infinite Scroll with Isotope. The initial group of items is laid out perfectly, but loading more items and adding them to the grid results in some odd layout problems (new items appearing underneath or overlapping other items.)

I realized I can reproduce what appears to be the same issue with one of your official demo codepens (see above). If you scroll through the grid quickly on Safari, image items appear beneath non-image items. 

Screenshot:
![image](https://user-images.githubusercontent.com/16673924/28938269-8c424d22-785b-11e7-855f-f8a4810e21b4.png)

**Comment by baxtr** [comment] 2017-08-03 20:41
I found that if you are loading images in your boxes and you specify the height and width of the images this problem seems to go away.  Give it a try if your boxes have images for content.

**Comment by desandro** [comment] 2017-08-04 13:31
Duplicate of #671 

Thanks for reporting this issue. Closing this one here. Follow progress there.

**Closed by desandro** 2017-08-04 13:31 UTC
