### ISSUE TITLE
Infinite scroll only loading one item and stops working.

### ISSUE THREAD

**Issue by clabm** [metafizzy/infinite-scroll#693] opened 2017-07-18 22:09 UTC
I have a site that I'm testing this on to see if it can meet our needs.
http://bit.ly/2tniguZ

I'm using Drupal 7 and have infinite scroll (3.0.0) tied in with our Flippy pager

The pages that it's working on seems to be random - working here - http://bit.ly/2tniguZ but only seems to load the next article ans stops working

this is the script I'm using right now:

``` js
$('.all-content-container').infiniteScroll({
  path: '.flippy .Previous',
  status: '.scroller-status',
  append: '.all-content',
  responseType: 'document',
  hideNav: '.flippy',
  history: 'replace',
  loadOnScroll: true,
  checkLastPage: false,
  debug: true,
});
```

I'm pretty sure I might be configuring something wrong, but wanted to see if anyone can offer any help. Thanks!

**Comment by dennishelbig** [comment] 2017-07-19 10:45
Same problem here

**Comment by desandro** [comment] 2017-07-19 13:18
Thanks for reporting this issue. It appears the issue is that your `path` element is contained within your `append` elements.

``` html
<div class="all-content-container">
  <div class="all-content">
    <ul class="flippy">
      <li class="prev">
        <a href="/soccer-news/italys-u-21s-just-cant-escape-controversy" title="Previous Article" class="Previous Article">Previous Article</a></li>
    </ul>
  </div>
</div>
```

So when Infinite Scroll looks to check if the `path` element `.flippy .Previous` is present, it's not, because Infinite Scroll has moved those elements.

To resolve this, I recommend moving your `path` element outside of the `append element.

``` html
<div class="all-content-container">
  <div class="all-content">
  </div>
  <ul class="flippy">
    <li class="prev">
      <a href="/soccer-news/italys-u-21s-just-cant-escape-controversy" title="Previous Article" class="Previous Article">Previous Article</a></li>
  </ul>
</div>
```

I realize this is a weird bug. Please add a 👍  reaction if ran into this issue as well. I may need to add a fix for this edge case.

**Comment by clabm** [comment] 2017-07-19 18:03
Thanks for the reply. I brought in flippy as a block and tried your suggestion and it still has the same issue. Any thoughts?

**Comment by desandro** [comment] 2017-07-20 12:34
This page http://dev.the18.com/soccer-news/soccer-wedding-season-summer does not work because Infinite Scroll expect's the `href` value of its `path` element to point to a url with a page number. I recommend you use the same technique as https://github.com/metafizzy/infinite-scroll/issues/688#issuecomment-316403688

As for the 2nd page not working. I can see the bug occurring, but I cannot debug this issue on your production site. If you can produce a **reduced test case** demonstrating the issue, I can better fix this issue. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by clabm** [comment] 2017-07-21 20:34
I ended up working the technique from #688 (comment) and decided to use the JS option instead of the jquery one. Everything is working fine now!

Looks like my next step is to work on re-loading our JS items and DFP ads.

**Closed** 2017-08-04 13:39 UTC
Labels: test case required
