### ISSUE TITLE
destroy() error

### ISSUE THREAD

**Issue by jesperlandberg** [metafizzy/infinite-scroll#695] opened 2017-07-26 13:10 UTC
Hi, thanks for a great plugin.

I'm receiving this error: 'this.button.destory is not a function' when trying to use destroy(). Seems like a type error in the source?

Any idea?

**Comment by desandro** [comment] 2017-07-27 18:17
Duplicate of #686 

Yes, This is a bug that will be fixed in the next release.

**Closed** 2017-08-04 13:36 UTC
Labels: duplicate
